server/routes/main.py
from flask import Flask, request, jsonify, Blueprint, render_template, flash, redirect, url_for

from server.helper import settings, cache
from server.models import Genome, Gene

import random

main = Blueprint("main", __name__)

@main.route("/")
def index():
    return(render_template("index.html"))

@main.route("/browse/<genome_name>/<gene_symbol>")
def browse(genome_name, gene_symbol):
    # I don't like that I'm loading the genome into memory each time
    # But this seems like the most elegant is is more scalable :)
    genome = Genome.load(genome_name) 
    if genome is None:
        flash("Genome not found", "alert-danger")
        return(render_template("index.html"))
    gene =  genome.get_gene_by_symbol(gene_symbol)
    if gene is None:
        flash("Gene not found", "alert-danger")
        return(render_template("index.html"))
    return(render_template("gene.html", 
                           gene=gene, 
                           transcripts=gene.get_transcripts_metadata()))

@main.route("/random/<genome_name>")
def random_gene(genome_name):
    allowed_types = ["protein-coding", "miRNA", "rRNA", "tRNA"]
    genome = Genome.load(genome_name)
    if genome is None:
        flash("Genome not found", "alert-danger")
        return(render_template("index.html"))
    gene = random.choice([gene for gene in genome.genes_table if gene["type"] in allowed_types])
    return(redirect(url_for("main.browse", genome_name=genome_name, gene_symbol=gene["symbol"])))

@main.route("/search/<genome_name>", methods=["GET"])
def search(genome_name):
    query = request.args.get("query")
    genome = Genome.load(genome_name)
    if query is None:
        flash("No query provided", "alert-danger")
        return(render_template("index.html"))
    if len(query) < 3:
        flash("Please provide a query with at least 3 characters", "alert-danger")
        return(render_template("index.html"))
    if genome is None:
        flash("Genome not found", "alert-danger")
        return(render_template("index.html"))
    results = genome.search(query)
    return(render_template("search.html", search_query=query, search_results=results))

@main.route("/robots.txt")
def robots():
    return(render_template("robots.txt"))

server/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap Icons, CSS, and JS -- Also jQuery -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}"" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-grid.min.css')}}"" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-reboot.min.css')}}"" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}"" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

    <!-- Main Script (for global functions) -->
    <script src="{{ url_for('static', filename='js/main.js')}}"></script>
    
    <!-- Add custom OpenGraph (and Twitter) content -->
    {% if custom_og %}
        <meta property="og:title" content="{{ custom_og['title'] }}" />
        <meta name="twitter:title" content="{{ custom_og['title'] }}" />
    {% else %}
        <meta property="og:title" content="EasyGeneDB" />
        <meta name="twitter:title" content="EasyGeneDB" />
    {% endif %}
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@quoctran98" />
    <meta property="og:description" content="An easy to use gene database!" />
    <meta name="twitter:description" content="An easy to use gene database!" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://easygenedb.net" />
    <meta property="og:image:url" content="{{ url_for('static', filename='img/favicon.png') }}" />
    <meta name="twitter:image" content="{{ url_for('static', filename='img/favicon.png') }}" />

    <title>EasyGeneDB.net</title>
</head>

<body>
    <div class="gets-blurred">

    <!-- PADDING ROW -->
    <div class="row"><div class="col-md-12"><br></div></div>

    <!-- HEADER -->
    <div class="row">

        <div class="col-md-2"></div>

        <div class="col-md-6 align-self-center">

            <!-- TITLE -->
            <a href="{{ url_for('main.index') }}" style="all: unset;">
                <h2 class="title" style="float: left;">
                    <img src="{{ url_for('static', filename='img/wordmark.png') }}" alt="EasyGeneDB.net wordmark" style="max-height: 2em; max-width: 90vw;">
                </h2>
            </a>

        </div>

        <div class="col-md-4 align-self-center">
        <div class="row">

            <!-- SEARCH BAR -->
            <form action="{{ url_for('main.search', genome_name='hg38') }}" method="GET" style="float: left;" id="top-search-bar">
                <div class="input-group">
                    <input type="text" class="form-control" name="query" placeholder="Search for a gene..." list="top-search-list">
                    <datalist id="top-search-list"></datalist>
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit"><i class="bi bi-search"></i></button>
                    </div>
                </div>
            </form>

            <!-- RANDOM GENE BUTTON -->
            <a href="{{ url_for('main.random_gene', genome_name='hg38') }}" style="float: right;">
                <button type="button" class="btn btn-primary" style="margin-left: 10px;"><i class="bi bi-dice-6"></i></button>
            </a>

        </div>
        </div>

     </div>
    </div>

    <hr>

    <!-- FLASH MESSAGES -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="container has-text-centered">
                <div class="alert {{ category }}" role="alert">
                    {{ message }}
                </div>
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    </div>

    <!-- CONTENT INSERTED BY DIFFERENT PAGES -->
    <div>
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
    </div>
</body>

<footer>
    <br>
    <hr>
    <div class="row gets-blurred">
        <div class="col-md-12">
            <p class="text-center" style="font-size:medium;">
                <!-- <a href="https://wikimediafoundation.org/support/" target="_blank" rel="noopener noreferrer"><img class="inline-image" src="{{ url_for('static', filename='img/Wikimedia-logo.png')}}"></img> Donate to the Wikimedia Foundation!</a> -->
                <!-- <br> -->
                <a href="https://github.com/quoctran98/EasyGeneDB/" target="_blank" rel="noopener noreferrer"><img class="inline-image" src="{{ url_for('static', filename='img/GitHub-Mark-32px.png')}}"></img> Github</a>
                <a href="https://twitter.com/quoctran98" target="_blank" rel="noopener noreferrer"><img class="inline-image" src="{{ url_for('static', filename='img/Twitter-Icon.png')}}"></img> Twitter</a>
                <a href="https://ko-fi.com/quoctran98" target="_blank" rel="noopener noreferrer"><img class="inline-image" src="{{ url_for('static', filename='img/Ko-fi-logo.png')}}"></img> Ko-fi</a>
                <br>
                QUO© 2024
                - 
                <a href="https://github.com/quoctran98/EasyGeneDB/issues" target="_blank" rel="noopener noreferrer">Report Issues</a>
                -
                <a href="#" target="_blank" rel="noopener noreferrer">Contact Me</a>
            </p>
        </div>
    </div>
</footer>

</html>

server/templates/gene.html
{% extends "base.html" %}

{% block content %}

<!-- HIDDEN DIV TO PASS DATA TO JAVASCRIPT -->
<div id="gene-data" style="display: none;">
    {{ serialize_json(gene.summary_dict) | safe }}
</div>
<div id="transcripts-list" style="display: none;">
    {{ serialize_json(transcripts) | safe }}
</div>

<!-- GENE NAME -->
<div class="row">
    <h3><b>{{ gene.name }}</b> ({{ gene.symbol }})</h3>
</div>

<!-- GENE SUMMARY -->
<!-- <div class="row">
    <p>This is a {{ gene.type }} gene</p>
</div> -->

<hr>

<!-- BIG TRANSCRIPTS LIST -->
<div class="row">    
    <div class="col-md-6">
        <p id="transcript-count" style="margin-bottom: 0rem;"">{{ gene.symbol }} encodes <b>{{ transcripts|length }} transcripts</b></p>

        <!-- CHECKBOXES -->
        <div class="input-group">
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="non-refseq" name="non-refseq" checked>
                <label class="form-check-label" for="non-refseq">Include non-RefSeq transcripts</label>
            </div>
        </div>

        <!-- DROPDOWN MENU -->
        <div class="input-group">
            <select class="form-control" name="all-transcripts" id="all-transcripts">
                {% for transcript in transcripts %}
                    <option value="{{ transcript.ncbi_accession }}">{{ transcript.product }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <!-- TRANSCRIPT INFORMATION TABLE -->
    <div class="col-md-4">
        <table class="table table-sm text-left" id="transcript-info-table" style="border-top:none">
            <tbody>
                <tr><td>NCBI Accession</td><td></td></tr>
                <tr><td>Annotation Source</td><td></td></tr>
                <!-- <tr><td>Curation Status</td><td></td></tr> --> <!-- It's redundant given the Annotation Source -->
                <tr><td>Transcript Bioype</td><td></td></tr>
            </tbody>
        </table>
    </div>
</div>

<hr>

<!-- GENOMIC CONTEXT / GENE MAP -->
<div class="row">
    <p>The <b>5′ end</b> of starts at <b>position {{ format_number(gene.locus[2] if gene.locus[1]=='plus' else gene.locus[3]) }} </b>
         on the <b>{{ gene.locus[1] }} strand</b> of <b>chromosome {{ gene.locus[0] }}</b></p>
</div>
<div class="row">
    <div id="gene-map" justify-content="center"></div>
</div>

<hr>

<div class="row">
<div class="col-md-9">
    <!-- DNA SEQUENCE -->
    <div class="row">
        <div class="input-group sequence-box" style="display:flex;" id="dna-sequence">
            <div class="input-group-prepend">
                <span class="input-group-text">Genomic DNA Sequence</span>
                <span class="input-group-text">5′</span>
            </div>
            <input type="text" id="seq" readonly="true" style="flex:1" value="{{ gene.sequence }}" maxlength="2147483647">
            <div class="input-group-append">
                <span class="input-group-text">3′</span>
                <span class="input-group-text" id="seq-length">{{ format_number(gene.sequence|length) }} bp</span>
                <button class="btn btn-secondary" onclick="copy_sequence(event, 'dna-sequence');"><i class="bi-clipboard"></i></button>
            </div>
        </div> 
    </div>

    <!-- PRE-RNA SEQUENCE -->
    <div class="row">
        <div class="input-group sequence-box" style="display:flex;" id="pre-rna-sequence">
            <div class="input-group-prepend">
                <span class="input-group-text">Full pre-RNA Sequence</span>
                <span class="input-group-text">5′</span>
            </div>
            <input type="text" id="seq" readonly="true" style="flex:1" value="" maxlength="2147483647">
            <div class="input-group-append">
                <span class="input-group-text">3′</span>
                <span class="input-group-text" id="seq-length"></span>
                <button class="btn btn-secondary" onclick="copy_sequence(event, 'pre-rna-sequence');"><i class="bi-clipboard"></i></button>
            </div>
        </div> 
    </div>

    <!-- SPLICED RNA SEQUENCE -->
    <div class="row">
        <div class="input-group sequence-box" style="display:flex;" id="spliced-rna-sequence">
            <div class="input-group-prepend">
                <span class="input-group-text">Spliced RNA Sequence</span>
                <span class="input-group-text">5′</span>
            </div>
            <input type="text" id="seq" readonly="true" style="flex:1" value="" maxlength="2147483647">
            <div class="input-group-append">
                <span class="input-group-text">3′</span>
                <span class="input-group-text" id="seq-length"></span>
                <button class="btn btn-secondary" onclick="copy_sequence(event, 'spliced-rna-sequence');"><i class="bi-clipboard"></i></button>
            </div>
        </div>
    </div>

    <!-- CODING RNA SEQUENCE -->
    <div class="row">
        <div class="input-group sequence-box" style="display:flex;" id="coding-rna-sequence">
            <div class="input-group-prepend">
                <span class="input-group-text">Coding RNA Sequence</span>
                <span class="input-group-text">5′</span>
            </div>
            <input type="text" id="seq" readonly="true" style="flex:1" value="" maxlength="2147483647">
            <div class="input-group-append">
                <span class="input-group-text">3′</span>
                <span class="input-group-text" id="seq-length"></span>
                <button class="btn btn-secondary" onclick="copy_sequence(event, 'coding-rna-sequence');"><i class="bi-clipboard"></i></button>
            </div>
        </div>
    </div>

    <!-- PROTEIN SEQUENCE -->
    <div class="row">
        <div class="input-group sequence-box" style="display:flex;" id="protein-sequence">
            <div class="input-group-prepend">
                <span class="input-group-text">Protein Sequence</span>
                <span class="input-group-text">N-term.</span>
            </div>
            <input type="text" id="seq" readonly="true" style="flex:1" value="" maxlength="2147483647">
            <div class="input-group-append">
                <span class="input-group-text">C-term.</span>
                <span class="input-group-text" id="seq-length"></span>
                <button class="btn btn-secondary" onclick="copy_sequence(event, 'protein-sequence');"><i class="bi-clipboard"></i></button>
            </div>
        </div>
    </div>
</div>
</div>

<br>

<!-- LINKS TO OTHER GENE DATABASES -->
<div class="row" id="database-xrefs">
    <p>View {{ gene.symbol }} in other databases:&emsp;</p>
    <a href="https://www.ncbi.nlm.nih.gov/gene/{{ gene.ncbi_gene_id }}" target="_blank">NCBI Gene <i class="bi bi-box-arrow-up-right"></i></a>
</div>

<script src="{{ url_for('static', filename='js/browse_gene.js') }}"></script>


{% endblock %}

server/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="gets-blurred">

<!-- <div class="alert alert-success" role="alert">
  Hi, thanks for using EasyGeneDB!
  You can open an issue on <a href="https://github.com/quoctran98/EasyGeneDB" target="_blank" rel="noopener noreferrer">GitHub</a> 
  or contact me.  - Quoc 
</div> -->

<!-- BIG SEARCH BAR -->
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h1 class="text-center">Welcome to EasyGeneDB!</h1>
    <p class="text-center">Search for a gene to get started. Or click the dice to get a random gene.</p>

      <form class="input-group mb-3" action="{{ url_for('main.search', genome_name='hg38') }}" method="GET" id="index-search-bar">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for a gene..." name="query" list="index-search-list">
          <datalist id="index-search-list"></datalist>
          <button class="btn btn-primary" type="submit"><i class="bi bi-search"></i></button>
          <a href="{{ url_for('main.random_gene', genome_name='hg38') }}" style="float: right;">
              <button type="button" class="btn btn-primary" style="margin-left: 10px;"><i class="bi bi-dice-6"></i></button>
          </a>
        </div>
      </form>

    </div>

  </div>
  <div class="col-md-2"></div>
</div>


<hr>

<!-- SITE EXPLANATION -->
<div style="color: black;">
    <h2>What is this?</h2>

    <p>So, the other week, I was writing a problem for the class that I was TA'ing,
      and I needed to get the spliced transcript of GAPDH so students could write a script
      to translate it to an amino acid sequence, but that's beside the point. So anyways,
      I popped on over to NCBI and typed "GAPDH" into the search bar, and I clicked on the
      first thing that showed up. It was the NCBI Gene page for GAPDH which made sense, but
      it quickly became too complicated to look for a transcript. And even when I did, it took
      me somewhere else, and I wasn't sure if it was like pre-mRNA or spliced or just the CDS or what. </p>

    <p>I got really frustrated and made this. It uses sequence information from the <b>GRCh38.p14 assembly</b> 
      of the human genome and annotations from <b>NCBI's RefSeq</b> to provide a simple interface 
      to look up genes, transcripts, and their sequences. There's also a random gene button that's fun to use. </p>

    <p>Anyways, if you have any questions or issues with the site, feel free to open an issue on the 
      <a href="https://github.com/quoctran98/EasyGeneDB/issues" target="_blank" rel="noopener noreferrer">GitHub page</a> or contact me. </p>

</div>

</div>

{% endblock %}

server/templates/search.html
{% extends "base.html" %}

{% block content %}

<div class="gets-blurred">

<!-- Search Results -->

<div class="row">
  <div class="col-md-2"></div>

  <div class="col-md-8">
    <h2>Search Results for '{{ search_query }}'</h2>

    <!-- DYNAMICALLY POPULATE CHECKBOXES -->
    <div id="checkbox-filters">
      <h4>Include results for:</h4>
      <div class="input-group" id="search-filters">
        {% for gene_type in get_unique_gene_types(search_results) %}
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="{{ gene_type }}" name="{{ gene_type }}" checked>
            <label class="form-check-label" for="{{ gene_type }}">{{ gene_type }}</label>
          </div>
        {% endfor %}
      </div>
    </div>

    <hr>

    {% if search_results == [] %}
      <p>No results found for '{{ search_query }}'.</p>
    {% endif %}

    {% for gene in search_results %}
      <div class="search-result-box" id="{{ gene.symbol }}">
        <div id="gene-data" style="display: none;">
          {{ serialize_json(gene.summary_dict) | safe }}
        </div>
        <a href="{{ url_for('main.browse', genome_name='hg38', gene_symbol=gene.symbol) }}">
          <h3>{{ gene.symbol }}</h3>
          <p>{{ gene.name }} (Chr. {{ gene.locus[0] }}) ({{ gene.type }})</p>
          <p>{{ gene.symbol }} encodes for {{ gene.transcripts|length }} transcript{{ "s" if gene.transcripts|length > 1 else "" }}.</p>
        </a>
      </div> 
    {% endfor %}
    

</div>

<!-- QUICK SCRIPT FOR THE SEARCH FILTERS -->
<script type="text/javascript">
  $(document).ready(function() {

    // If there's only one checkbox, disable #checkbox-filters child
    if ($("#search-filters input").length == 1) {
      $("#checkbox-filters h4").css("color", "gray");
      $("#search-filters input").prop("disabled", true);
    }

    // Add an event listener to each checkbox in the search filters
    $("#search-filters input").change(function() {

      // Loop through each search result box to see if it should be hidden or shown
      all_search_results = $(".search-result-box");
      for (search_result of all_search_results) {
        let gene_symbol = $(search_result).attr("id");
        let gene_data = JSON.parse($(`#${gene_symbol} #gene-data`).text());
        let gene_type = gene_data["type"];
        console.log(gene_symbol, gene_type);

        // Check if the gene type is in the search filters
        const all_filter_names = $("#search-filters input").map(function() {return $(this).attr("id");}).get();
        let show_gene = false;
        
        for (filter_name of all_filter_names) {
          const checked = $("#" + filter_name).is(":checked");
          if (gene_type == filter_name && checked) {
            show_gene = true;
            break;
          }
        }

        // Show or hide the gene based on the search filters
        // It's confusing but now "this" refers to the search result box
        if (show_gene) {
          $(search_result).show();
        } else {
          $(search_result).hide();
        }
      }
    });
  });

</script>

{% endblock %}